
services:
  api:
    container_name: inventory-managment-api
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./api/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:latest
    # ports:
    #   - "33060:33060"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
